import type { GenreFamily } from './genre-families.ts';

export type GenreSlug =
  | 'tien_hiep' | 'huyen_huyen' | 'vo_thuat' | 'cao_vo' | 'do_thi' | 'di_nang'
  | 'mat_the' | 'khoa_huyen' | 'kiem_hiep' | 'tu_chan' | 'di_gioi' | 'he_thong'
  | 'trong_sinh' | 'xuyen_khong' | 'lich_su_gia_tuong' | 'cung_dau' | 'linh_di'
  | 'trinh_tham' | 'quan_su' | 'tay_huyen' | 'dong_phuong_huyen_bi' | 'vong_du'
  | 'hac_am_fantasy' | 'do_thi_tu_tien' | 'do_thi_di_nang' | 'tuy_chon';

export type GenreDef = {
  slug: GenreSlug;
  viLabel: string;
  viDescription: string;
  family: GenreFamily;
  allowedTropes: string[];
  discouragedTropes: string[];
  toneGuidance: string;
  worldbuildingGuidance: string;
  examplePremises: string[];
};

export const GENRES: readonly GenreDef[] = [
  {
    slug: 'tien_hiep',
    viLabel: 'Tiên hiệp',
    viDescription: 'Tu luyện cảnh giới, tông môn, pháp bảo, huyết mạch, khí vận, đại đạo.',
    family: 'cultivation',
    allowedTropes: ['tu luyện', 'cảnh giới', 'đột phá', 'tông môn', 'pháp bảo', 'huyết mạch', 'linh khí', 'đan dược', 'bí cảnh', 'khí vận', 'phi thăng'],
    discouragedTropes: ['súng đạn hiện đại', 'điện thoại di động', 'AI', 'internet'],
    toneGuidance: 'Cinematic, có nội tâm; "show, don\'t tell"; tránh harem mặc định và "ding hệ thống".',
    worldbuildingGuidance: 'Thế giới có cảnh giới rõ ràng, tông môn-thế gia, đại lục/châu lục/thiên giới.',
    examplePremises: ['Một phế vật bị đuổi khỏi gia tộc, vô tình thừa kế truyền thừa thượng cổ.'],
  },
  {
    slug: 'huyen_huyen',
    viLabel: 'Huyền huyễn',
    viDescription: 'Thế giới huyền ảo có hệ thống huyết mạch/đạo/luật tắc, mạnh hơn tiên hiệp về quy mô vũ trụ.',
    family: 'cultivation',
    allowedTropes: ['huyết mạch thần thoại', 'thiên đạo', 'luật tắc', 'thế giới', 'thần ma', 'đại đế', 'long tộc', 'thần thú', 'thượng cổ truyền thừa'],
    discouragedTropes: ['súng đạn hiện đại', 'AI', 'điện thoại', 'công ty hiện đại'],
    toneGuidance: 'Vĩ mô, có cảm giác thiên địa rộng lớn; tránh tu vi cảnh giới quá kỹ thuật như tiên hiệp thuần.',
    worldbuildingGuidance: 'Có nhiều thế giới/đại lục; hệ thống huyết mạch là trục chính, không nhất thiết tu luyện theo cảnh giới linh khí.',
    examplePremises: ['Một thiếu niên thức tỉnh huyết mạch thần long bị tuyệt diệt thượng cổ.'],
  },
  {
    slug: 'vo_thuat',
    viLabel: 'Võ thuật',
    viDescription: 'Giang hồ, môn phái, võ công, nội lực — không có tu tiên / tiên giới.',
    family: 'martial',
    allowedTropes: ['giang hồ', 'võ công', 'môn phái', 'nội lực', 'kinh mạch', 'ám khí', 'thần binh', 'tâm pháp', 'khinh công'],
    discouragedTropes: ['tu tiên', 'cảnh giới linh khí', 'pháp bảo', 'phi thăng', 'huyết mạch tiên đạo'],
    toneGuidance: 'Tinh tế, có triết lý võ học; conflict gắn với danh dự, ân oán giang hồ.',
    worldbuildingGuidance: 'Bối cảnh cổ trang/cận đại; có đại môn phái và tà giáo; không có cảnh giới tu tiên.',
    examplePremises: ['Một thiếu niên mồ côi vô tình học được tuyệt thế võ công, dấn thân vào ân oán giang hồ.'],
  },
  {
    slug: 'cao_vo',
    viLabel: 'Cao võ',
    viDescription: 'Thế giới võ lực cá nhân cao, hệ thống cấp bậc chiến lực, học viện/quân đội/võ đạo.',
    family: 'martial',
    allowedTropes: ['cấp chiến lực', 'võ giả', 'học viện võ', 'dị thú', 'chiến trường', 'kỹ năng võ', 'nội lực', 'hấp thụ năng lượng'],
    discouragedTropes: ['tu tiên thuần', 'phi thăng tiên giới', 'pháp bảo cổ điển', 'linh căn tu chân'],
    toneGuidance: 'Hành động dồn dập, có phân tích chiến đấu, tránh triết lý đạo quá nhiều.',
    worldbuildingGuidance: 'Có hệ thống cấp bậc võ giả rõ ràng (vd 9 cấp); có học viện hoặc quân đoàn võ.',
    examplePremises: ['Một thiếu niên nghèo gia nhập học viện võ đạo bằng tài năng dị biệt.'],
  },
  {
    slug: 'do_thi',
    viLabel: 'Đô thị',
    viDescription: 'Bối cảnh thành phố hiện đại, conflict tiền bạc/quyền lực/bí mật/gia đình.',
    family: 'urban',
    allowedTropes: ['công ty', 'gia tộc hiện đại', 'tổ chức ngầm', 'thương trường', 'âm mưu chính trị', 'truyền thông', 'mạng xã hội'],
    discouragedTropes: ['tu tiên', 'linh căn', 'cảnh giới', 'tông môn', 'pháp bảo', 'huyết mạch tiên đạo', 'phi thăng', 'tiên giới'],
    toneGuidance: 'Hiện thực gần đời thường, dialogue tự nhiên, tiết tấu vừa phải.',
    worldbuildingGuidance: 'Thành phố lớn, công ty/tập đoàn, gia đình, xã hội. KHÔNG bắt buộc có siêu năng lực.',
    examplePremises: ['Một nhân viên trẻ phát hiện sếp mình đang tham ô và bị cuốn vào âm mưu lớn hơn.'],
  },
  {
    slug: 'di_nang',
    viLabel: 'Dị năng',
    viDescription: 'Năng lực đặc biệt, tổ chức ngầm, thí nghiệm, xã hội hiện đại hoặc bán hiện đại.',
    family: 'ability',
    allowedTropes: ['siêu năng lực', 'awakening', 'tổ chức bí mật', 'cơ quan chính phủ ẩn', 'thí nghiệm', 'mutant', 'năng lực phụ'],
    discouragedTropes: ['tu tiên', 'cảnh giới', 'tông môn', 'pháp bảo', 'phi thăng', 'cổ trang huyền huyễn'],
    toneGuidance: 'Pha trộn realism + supernatural; conflict gắn với khám phá năng lực và tổ chức.',
    worldbuildingGuidance: 'Hiện đại hoặc bán hiện đại; có "thế giới ngầm" của người có năng lực.',
    examplePremises: ['Một sinh viên y khoa bỗng dưng thức tỉnh năng lực chữa lành và bị săn đuổi.'],
  },
  {
    slug: 'mat_the',
    viLabel: 'Mạt thế',
    viDescription: 'Hậu tận thế, sống sót giữa zombie/biến dị, tài nguyên khan hiếm.',
    family: 'mixed',
    allowedTropes: ['zombie', 'biến dị thú', 'cứ điểm sinh tồn', 'tài nguyên khan hiếm', 'bóng tối nhân tính', 'phe phái sinh tồn', 'thức tỉnh năng lực sau tận thế'],
    discouragedTropes: ['tu tiên cảnh giới truyền thống', 'tông môn cổ điển', 'cung đấu hậu cung'],
    toneGuidance: 'U tối, căng thẳng; tính người bị bào mòn; ít tiếng cười.',
    worldbuildingGuidance: 'Thế giới sau biến cố lớn (virus / thiên thạch / chiến tranh); cấu trúc xã hội sụp đổ.',
    examplePremises: ['Ngày tận thế thứ ba, một nhân viên văn phòng phát hiện mình thức tỉnh năng lực điều khiển nước.'],
  },
  {
    slug: 'khoa_huyen',
    viLabel: 'Khoa huyễn',
    viDescription: 'Sci-fi: tương lai gần/xa, công nghệ tiên tiến, vũ trụ học, AI, sinh học cải tạo.',
    family: 'tech',
    allowedTropes: ['mecha', 'AI', 'tinh hệ', 'tàu vũ trụ', 'cyberpunk', 'sinh học cải tạo', 'năng lượng đen', 'teleport công nghệ', 'chiến hạm', 'thuộc địa hành tinh'],
    discouragedTropes: ['tu tiên cảnh giới', 'huyết mạch tiên đạo', 'pháp bảo cổ điển', 'tông môn võ thuật'],
    toneGuidance: 'Logic công nghệ chặt; conflict gắn với khám phá, chiến tranh tinh hệ, đạo đức AI.',
    worldbuildingGuidance: 'Tương lai có công nghệ rõ ràng (cấp độ Kardashev); có thể có ngoài hành tinh, nội chiến tinh hệ.',
    examplePremises: ['Một kỹ sư AI phát hiện chương trình mình viết đã thức tỉnh tự ý thức.'],
  },
  {
    slug: 'kiem_hiep',
    viLabel: 'Kiếm hiệp',
    viDescription: 'Truyền thống Kim Dung/Cổ Long: giang hồ, kiếm khách, thi từ, cấu trúc cổ điển.',
    family: 'martial',
    allowedTropes: ['kiếm khách', 'môn phái lớn (Thiếu Lâm/Võ Đang)', 'tà giáo', 'bí kíp', 'tâm pháp kiếm', 'tửu lâu', 'giang hồ phong vận', 'ám khí', 'cao thủ ẩn cư'],
    discouragedTropes: ['cảnh giới tu tiên', 'phi thăng', 'pháp bảo cổ điển kiểu tiên hiệp', 'súng đạn'],
    toneGuidance: 'Có chất thi văn cổ; nhân vật có triết lý nhân sinh; conflict ân oán đậm chất nho-phật-đạo.',
    worldbuildingGuidance: 'Cổ trang Trung Hoa hoặc dị bản; có Đại Lý/Đại Tống/Tây Vực; có ngũ nhạc/cửu phái.',
    examplePremises: ['Một kiếm khách trẻ đi tìm sư phụ bị giết, vô tình bị cuốn vào tranh đoạt bí kíp tuyệt thế.'],
  },
  {
    slug: 'tu_chan',
    viLabel: 'Tu chân',
    viDescription: 'Tu chân thuần — cảnh giới chi tiết hơn tiên hiệp, ít chất thi văn, nhiều hệ thống.',
    family: 'cultivation',
    allowedTropes: ['cảnh giới tu chân chi tiết (luyện khí/trúc cơ/kim đan/...)', 'pháp bảo', 'đan dược', 'tông môn nhỏ', 'lệch thiên', 'bí cảnh', 'truyền thừa thượng cổ'],
    discouragedTropes: ['súng đạn', 'AI', 'thành phố hiện đại', 'tổ chức ngầm hiện đại'],
    toneGuidance: 'Trung thành với cảnh giới đột phá; conflict đa phần là tài nguyên / pháp bảo / truyền thừa.',
    worldbuildingGuidance: 'Thế giới tu chân có cảnh giới rõ ràng, tông môn nhiều cấp; thiên đạo nghiêm khắc.',
    examplePremises: ['Một phế vật mạch loạn vô tình nhận truyền thừa từ một thượng cổ chân nhân.'],
  },
  {
    slug: 'di_gioi',
    viLabel: 'Dị giới',
    viDescription: 'Western fantasy hoặc isekai: hiệp sĩ, ma pháp sư, đế quốc, dị tộc, dungeon.',
    family: 'mixed',
    allowedTropes: ['ma pháp', 'hiệp sĩ', 'đế quốc', 'elf/dwarf/orc', 'dungeon', 'thánh nữ', 'long', 'kỵ sĩ', 'guild phiêu lưu giả'],
    discouragedTropes: ['tu tiên cảnh giới Đông phương', 'tông môn', 'pháp bảo Đông phương', 'phi thăng tiên giới'],
    toneGuidance: 'Có chất Tây phương fantasy; conflict thường là chiến tranh đế quốc, ma vương, dungeon exploration.',
    worldbuildingGuidance: 'Đại lục Tây phương fantasy; có ma pháp, magic circle, mana, hệ thống job/class.',
    examplePremises: ['Một học sinh Nhật Bản tỉnh dậy trong thân thể một quý tộc trẻ ở đế quốc ma pháp.'],
  },
  {
    slug: 'he_thong',
    viLabel: 'Hệ thống',
    viDescription: 'Nhân vật chính có "system" gắn vào não — task/reward/stat panel/skill.',
    family: 'system',
    allowedTropes: ['system panel', 'daily quest', 'reward', 'skill book', 'level up', 'achievement', 'inventory', 'check-in', 'reincarnation host'],
    discouragedTropes: ['phong cách thuần văn học không có UI system', 'tu tiên không system'],
    toneGuidance: 'Có cảm giác game-ified; nhịp nhanh, reward-driven; có thể hài hước.',
    worldbuildingGuidance: 'Bối cảnh đa dạng (đô thị, dị giới, tu tiên đều được) miễn có "system" rõ ràng.',
    examplePremises: ['Một nhân viên giao hàng bị xe tông, tỉnh dậy với "Hệ thống Gánh team" trong đầu.'],
  },
  {
    slug: 'trong_sinh',
    viLabel: 'Trọng sinh',
    viDescription: 'Nhân vật chính chết và sống lại trong quá khứ với ký ức tương lai.',
    family: 'reincarnation',
    allowedTropes: ['ký ức tương lai', 'báo thù ngườذi phản bội', 'sửa chữa sai lầm', 'tận dụng thông tin', 'nhân quả', 'kiếp trước/kiếp này'],
    discouragedTropes: ['mất ký ức tương lai sớm vô lý', 'tự sự không tận dụng prophecy'],
    toneGuidance: 'Có cảm giác "bù đắp" nhanh chóng; conflict gắn với quá khứ đã thay đổi.',
    worldbuildingGuidance: 'Thế giới có thể là bất kỳ (đô thị/tiên hiệp/dị giới); trục là nhân vật chính có lợi thế thông tin.',
    examplePremises: ['Một CEO bị vợ hãm hại trọng sinh về thờذi sinh viên, quyết tâm thay đổi vận mệnh.'],
  },
  {
    slug: 'xuyen_khong',
    viLabel: 'Xuyên không',
    viDescription: 'Nhân vật chính từ thế giới hiện đại xuyên về cổ đại / dị giới / game.',
    family: 'reincarnation',
    allowedTropes: ['xuyên không bằng tai nạn / system / cổ vật', 'ưu thế kiến thức hiện đại', 'mâu thuẫn văn hoá', 'xây dựng thế lực', 'phát minh thờذi đại'],
    discouragedTropes: ['quên gốc gác hiện đại quá nhanh', 'không có cú sốc văn hoá'],
    toneGuidance: 'Có cảm giác fish-out-of-water giai đoạn đầu; sau đó nhân vật trở thành nhân vật chủ chốt thờذi đại.',
    worldbuildingGuidance: 'Phần lớn ở thế giớذi đến (cổ đại Trung Hoa / dị giới / game), giữ chút ký ức hiện đại.',
    examplePremises: ['Một bác sĩ trẻ xuyên không về thờذi chiến quốc với toàn bộ kiến thức y học hiện đại.'],
  },
  {
    slug: 'lich_su_gia_tuong',
    viLabel: 'Lịch sử giả tưởng',
    viDescription: 'Thế giới dựa trên lịch sử có thật nhưng nhánh thay đổi (alt-history).',
    family: 'historical',
    allowedTropes: ['triều đại lịch sử', 'nhân vật lịch sử có thật', 'chiến trận lớn', 'biến cố alt-history', 'chính trị triều đình', 'binh pháp'],
    discouragedTropes: ['tu tiên cảnh giới', 'pháp bảo huyền huyễn', 'năng lực siêu nhiên không có context lịch sử'],
    toneGuidance: 'Có cảm giác sử thi; chú trọng chi tiết thờذi đại (trang phục, lễ chế, ngôn ngữ).',
    worldbuildingGuidance: 'Phải research lịch sử cẩn thận; alt-history phải có "điểm rẽ" (point of divergence) rõ ràng.',
    examplePremises: ['Một sử gia trẻ trọng sinh thành Lưu Bang trước khi khởi binh chống Tần.'],
  },
  {
    slug: 'cung_dau',
    viLabel: 'Cung đấu',
    viDescription: 'Đấu đá hậu cung / triều đình; conflict tâm cơ, chính trị.',
    family: 'historical',
    allowedTropes: ['hậu cung', 'phi tần', 'tâm cơ', 'âm mưu chính trị', 'phái hệ triều đình', 'tỳ nữ thân tín', 'thái hậu', 'sủng ái hoàng đế'],
    discouragedTropes: ['tu tiên', 'năng lực siêu nhiên', 'súng đạn', 'công nghệ hiện đại'],
    toneGuidance: 'Tinh tế, có chiều sâu tâm lý; conflict ngầm nhiều hơn xung đột công khai.',
    worldbuildingGuidance: 'Triều đình cổ trang Đông phương; có cấp bậc phi tần rõ ràng; gia tộc lớn ngoài cung.',
    examplePremises: ['Một thiên kim tiểu thư bị gia tộc dùng làm con cờ tiến cung, dần dần lộ ra dã tâm.'],
  },
  {
    slug: 'linh_di',
    viLabel: 'Linh dị',
    viDescription: 'Truyện ma / kinh dị / linh hồn — bầu không khí ám ảnh, jump scare.',
    family: 'horror',
    allowedTropes: ['ma quỷ', 'thầy pháp', 'âm dương sư', 'oan hồn', 'lễ nghi cổ', 'cõi âm', 'bùa chú', 'ngôi nhà ma', 'thân nguyền'],
    discouragedTropes: ['tu tiên cảnh giới truyền thống', 'pháp bảo nhẹ nhàng', 'cảnh hài hước phá tan không khí'],
    toneGuidance: 'Ám ảnh, slow burn, dùng âm thanh/mùi/ánh sáng tạo bầu không khí.',
    worldbuildingGuidance: 'Có hệ thống tâm linh (âm dương / ngũ hành); cõi âm và cõi dương ranh giớذi mỏng.',
    examplePremises: ['Một sinh viên báo chí tình nguyện ở một làng cổ và phát hiện cả làng đã chết hơn trăm năm.'],
  },
  {
    slug: 'trinh_tham',
    viLabel: 'Trinh thám',
    viDescription: 'Phá án, suy luận logic, manh mối, twist cuối.',
    family: 'mystery',
    allowedTropes: ['vụ án', 'manh mối', 'suy luận logic', 'thám tử', 'cảnh sát', 'hung thủ', 'phá án', 'hiện trường', 'pháp y'],
    discouragedTropes: ['tu tiên giải đố bằng phép thuật', 'năng lực ngoại cảm dễ dãi (trừ khi xuyên suốt)', 'kết thúc deus ex machina'],
    toneGuidance: 'Logic chặt; manh mối phải fair (reader có thể tự suy ra); twist cuối phải có foreshadowing.',
    worldbuildingGuidance: 'Hiện đại hoặc bán hiện đại; có hệ thống cảnh sát/pháp y rõ ràng.',
    examplePremises: ['Một thám tử tư trẻ nhận vụ án tự sát của một nữ doanh nhân, phát hiện không phải tự sát.'],
  },
  {
    slug: 'quan_su',
    viLabel: 'Quân sự',
    viDescription: 'Chiến tranh hiện đại / cổ đại, binh pháp, chỉ huy chiến trận.',
    family: 'historical',
    allowedTropes: ['binh pháp', 'tướng lĩnh', 'chiến trận', 'hậu cần', 'tình báo quân sự', 'đặc nhiệm', 'liên minh quân sự', 'bộ tham mưu'],
    discouragedTropes: ['tu tiên 1-vs-vạn', 'pháp bảo phá thành', 'hậu cung yêu nhau giữa chiến trận'],
    toneGuidance: 'Logic chiến thuật; tôn trọng tổn thất nhân mạng; không lý tưởng hoá chiến tranh.',
    worldbuildingGuidance: 'Có cấp bậc quân đội rõ ràng; có học viện quân sự / binh đoàn / hậu cần.',
    examplePremises: ['Một sỹ quan trẻ được giao chỉ huy đơn vị tan tác và phải rebuild trong 3 tháng.'],
  },
  {
    slug: 'tay_huyen',
    viLabel: 'Tây huyền',
    viDescription: 'Western fantasy có chất ma pháp Đông-Tây pha trộn; mạnh hơn dị giới về quy mô vũ trụ.',
    family: 'mixed',
    allowedTropes: ['ma pháp đa hệ', 'thần ma chiến', 'long', 'thiên thần / ác quỷ', 'magic academy', 'tinh tinh thiên thể', 'mana', 'phù văn'],
    discouragedTropes: ['tu tiên Đông phương thuần', 'tông môn nội lực'],
    toneGuidance: 'Có quy mô vũ trụ; conflict bao gồm phe phái thần ma; nhịp epic.',
    worldbuildingGuidance: 'Đại lục có nhiều chủng tộc; ma pháp có hệ thống học thuật; có thần điện và ác quỷ giớذi.',
    examplePremises: ['Một cô bé mồ côi vô tình thừa kế ma lực của một thần đã chết.'],
  },
  {
    slug: 'dong_phuong_huyen_bi',
    viLabel: 'Đông phương huyền bí',
    viDescription: 'Pha trộn võ thuật + linh dị + tu tiên nhẹ + thầy bói/phong thuỷ.',
    family: 'mixed',
    allowedTropes: ['phong thuỷ', 'bói toán', 'thầy pháp', 'âm dương sư', 'võ thuật cổ', 'long mạch', 'cổ thuật', 'di chỉ thượng cổ', 'biểu tượng huyền học'],
    discouragedTropes: ['tu tiên cảnh giới chi tiết kiểu tu chân', 'súng đạn hiện đại lạm dụng'],
    toneGuidance: 'Bí ẩn, có chiều sâu văn hoá Đông phương; nhịp chậm rãi xen action.',
    worldbuildingGuidance: 'Cổ trang hoặc cận hiện đại có yếu tố huyền học truyền thống.',
    examplePremises: ['Một thầy phong thuỷ trẻ kế thừa nghề gia tộc, được giao xem long mạch một mỏ vàng.'],
  },
  {
    slug: 'vong_du',
    viLabel: 'Võng du',
    viDescription: 'Bối cảnh trong game online / VR; nhân vật chính chơi game.',
    family: 'tech',
    allowedTropes: ['VR helmet', 'guild', 'PVP', 'PVE', 'level', 'item drop', 'auction house', 'beta tester', 'hidden quest', 'top player'],
    discouragedTropes: ['rờذi game vĩnh viễn quá sớm', 'tu tiên cảnh giớذi ngoài game'],
    toneGuidance: 'Có cảm giác game-y; thuật ngữ game; nhịp nhanh; có pacing PVE/PVP.',
    worldbuildingGuidance: 'Game online (MMORPG) hoặc VR; có hệ thống job/skill/level rõ ràng.',
    examplePremises: ['Một game thủ pro trở lại sau khi giải nghệ vào ngày game ra phiên bản mớذi.'],
  },
  {
    slug: 'hac_am_fantasy',
    viLabel: 'Hắc ám fantasy',
    viDescription: 'Grimdark — fantasy nhưng đen tối, đạo đức xám, không có anh hùng thuần.',
    family: 'horror',
    allowedTropes: ['đạo đức xám', 'hi sinh không cần thiết', 'phản anh hùng', 'thế giớذi sụp đổ', 'thần đã chết', 'lờذi nguyền cổ', 'phe phái đều xấu'],
    discouragedTropes: ['anh hùng cứu thế giớذi đơn thuần', 'happy ending dễ dãi', 'romance dễ dãi'],
    toneGuidance: 'U tối, không lý tưởng hoá; tránh cliché "ánh sáng thắng bóng tối".',
    worldbuildingGuidance: 'Fantasy nhưng có yếu tố grimdark — đế quốc tàn ác, magic có giá đắt, thần đã chết hoặc thờذi ơ.',
    examplePremises: ['Một sát thủ đã giết quá nhiều ngườذi được giao nhiệm vụ cuối: ám sát chính sư phụ mình.'],
  },
  {
    slug: 'do_thi_tu_tien',
    viLabel: 'Đô thị tu tiên',
    viDescription: 'Tu tiên trong bối cảnh đô thị hiện đại — pha trộn cảnh giớذi + công ty/gia đình.',
    family: 'cultivation',
    allowedTropes: ['cảnh giớذi tu tiên ẩn', 'tông môn ẩn thế hiện đại', 'pháp bảo trong đô thị', 'huyền môn', 'gia tộc tu tiên', 'thí luyện hiện đại', 'cao thủ ẩn cư trong thành phố'],
    discouragedTropes: ['hoàn toàn cổ trang không có yếu tố hiện đại', 'sci-fi quá đậm'],
    toneGuidance: 'Pha trộn không khí đô thị + tu tiên; conflict thường là tu giả vs phàm nhân, hoặc tông môn nhỏ vs gia tộc lớn.',
    worldbuildingGuidance: 'Thành phố hiện đại có "thế giớذi tu giả" ẩn; tông môn vận hành dưới vỏ bọc công ty/gia tộc.',
    examplePremises: ['Một sinh viên nghèo vô tình nhận truyền thừa của một tu sĩ cổ đại trong căn nhà cũ.'],
  },
  {
    slug: 'do_thi_di_nang',
    viLabel: 'Đô thị dị năng',
    viDescription: 'Năng lực đặc biệt + bối cảnh đô thị hiện đại — gần dị năng nhưng đậm chất thành phố.',
    family: 'ability',
    allowedTropes: ['siêu năng lực', 'awakening', 'tổ chức ngầm hiện đại', 'cơ quan chính phủ ẩn', 'experiment', 'mutant', 'gia tộc dị năng', 'năng lực gia phả'],
    discouragedTropes: ['tu tiên cảnh giớذi', 'tông môn cổ điển', 'pháp bảo cổ điển'],
    toneGuidance: 'Hiện đại hoá; conflict gắn với khám phá năng lực + tổ chức ngầm; ít chất tu tiên.',
    worldbuildingGuidance: 'Thành phố hiện đại có "thế giớذi ngầm" của ngườذi có năng lực; có cơ quan quản lý.',
    examplePremises: ['Một nhân viên IT bị tai nạn ở phòng thí nghiệm bí mật, thức tỉnh năng lực điều khiển kim loại.'],
  },
  {
    slug: 'tuy_chon',
    viLabel: 'Tuỳ chọn (do bible quyết định)',
    viDescription: 'Không ràng buộc thể loại — model bám sát bible làm nguồn duy nhất.',
    family: 'none',
    allowedTropes: [],
    discouragedTropes: [],
    toneGuidance: 'Bám sát bible đã được duyệt; không thiên về thể loại nào.',
    worldbuildingGuidance: 'Bible là nguồn duy nhất; không tự ý đưa trope mớذi.',
    examplePremises: [],
  },
];
