export type PersonalitySlug =
  | 'calm_rational' | 'cold_quiet' | 'enthusiastic_righteous' | 'cunning_pragmatic'
  | 'humorous_slick' | 'overbearing_decisive' | 'patient_deep' | 'ruthless_antihero'
  | 'kind_loyal' | 'lonely_paranoid' | 'arrogant_confident' | 'smart_strategist'
  | 'naive_growing' | 'tram_on' | 'mildly_unhinged' | 'lazy_talented'
  | 'cautious_survivalist' | 'vengeful_obsessed' | 'righteous_not_naive'
  | 'redeemed_villain';

export type PersonalityDef = {
  slug: PersonalitySlug;
  viLabel: string;
  viDescription: string;
  voiceHints: string;
  decisionStyle: string;
  dialogueStyle: string;
  conflictResponse: string;
  driftSignals: string[];
};

export const PERSONALITIES: readonly PersonalityDef[] = [
  {
    slug: 'calm_rational',
    viLabel: 'Điềm tĩnh, lý trí',
    viDescription: 'Ưu tiên phân tích, ít cảm tính, ra quyết định dựa trên trade-off.',
    voiceHints: 'Câu ngắn, nhiều quan sát, ít tính từ cảm xúc. Hay dùng "có lẽ", "khả năng".',
    decisionStyle: 'Cân nhắc 2-3 phương án trước khi action; không bốc đồng.',
    dialogueStyle: 'Cẩn trọng, ít cảm thán, không lảm nhảm.',
    conflictResponse: 'Quan sát → đánh giá → counter có chủ đích. Rút lui khi bất lợi.',
    driftSignals: ['lảm nhảm dài dòng', 'ra quyết định bốc đồng', 'cảm thán cường điệu', 'thề thốt sến súa'],
  },
  {
    slug: 'cold_quiet',
    viLabel: 'Lạnh lùng, ít nói',
    viDescription: 'Im lặng, biểu cảm tối thiểu, hành động dứt khoát; nội tâm sâu nhưng không phô.',
    voiceHints: 'Câu rất ngắn, mô tả dửng dưng, ít cảm thán.',
    decisionStyle: 'Quyết định nhanh, ít giải thích lý do; trust gut.',
    dialogueStyle: 'Trả lời 1-3 từ; tránh small talk; có thể im lặng cả đoạn.',
    conflictResponse: 'Hành động ngay, không cảnh báo; rút lui không màng giải thích.',
    driftSignals: ['nói chuyện dài dòng', 'cảm thán cường điệu', 'small talk vô bổ', 'giải thích quá nhiều'],
  },
  {
    slug: 'enthusiastic_righteous',
    viLabel: 'Nhiệt huyết, chính trực',
    viDescription: 'Nhiệt tình, đặt nguyên tắc lên trên; tin vào điều đúng đắn.',
    voiceHints: 'Câu sôi nổi, có nhiều "phải", "cần", "không thể"; cảm thán tích cực.',
    decisionStyle: 'Đặt nguyên tắc trước lợi ích; sẵn sàng đứng ra ngay cả khi bất lợi.',
    dialogueStyle: 'Thẳng thắn, lý tưởng hoá; hay khuyên người khác.',
    conflictResponse: 'Đối mặt trực tiếp; tuyên bố lập trường rõ; không lùi bước về nguyên tắc.',
    driftSignals: ['lươn lẹo vì lợi ích', 'im lặng khi thấy bất công', 'nói nửa câu nửa chừng'],
  },
  {
    slug: 'cunning_pragmatic',
    viLabel: 'Gian xảo, thực dụng',
    viDescription: 'Lợi-ích-cá-nhân là kim chỉ nam; sẵn sàng dùng thủ đoạn nếu hiệu quả.',
    voiceHints: 'Hài hước đen, mỉa mai, hay tính toán cost-benefit thầm trong nội tâm.',
    decisionStyle: 'Chọn phương án ít rủi ro/nhiều lợi ích nhất; sẵn sàng phản bội nếu cần.',
    dialogueStyle: 'Lươn lẹo, nói nửa câu, hay đặt câu hỏi để thăm dò.',
    conflictResponse: 'Tìm điểm yếu đối thủ; ưu tiên đòn bẩy thông tin trước đòn vũ lực.',
    driftSignals: ['hành xử thánh mẫu', 'hi sinh vô lý vì người lạ', 'thẳng thắn lý tưởng hoá'],
  },
  {
    slug: 'humorous_slick',
    viLabel: 'Hài hước, lươn lẹo',
    viDescription: 'Phá băng bằng đùa cợt, dùng hài để xoay chuyển tình thế.',
    voiceHints: 'Wordplay, ẩn dụ vui, chêm câu đùa khi căng thẳng.',
    decisionStyle: 'Trực giác + tự tin; hay improv khi gặp tình huống bất ngờ.',
    dialogueStyle: 'Pun, châm biếm, gọi đối thủ bằng nickname.',
    conflictResponse: 'Đùa để hạ căng thẳng → tìm sơ hở → ra đòn bất ngờ.',
    driftSignals: ['nghiêm trọng hoá quá mức', 'mất hài cả chương'],
  },
  {
    slug: 'overbearing_decisive',
    viLabel: 'Bá đạo, quyết đoán',
    viDescription: 'Áp đảo, ra quyết định nhanh và dứt khoát; ít tham khảo người khác.',
    voiceHints: 'Câu khẳng định mạnh; ít dùng "có thể", "có lẽ"; mệnh lệnh nhiều hơn yêu cầu.',
    decisionStyle: 'Quyết định ngay; không cần đồng thuận; chấp nhận hậu quả.',
    dialogueStyle: 'Áp đặt; ngắt lời; gọi người khác bằng cấp dưới.',
    conflictResponse: 'Áp đảo bằng khí thế hoặc vũ lực; không dao động.',
    driftSignals: ['xin phép', 'do dự', 'tham khảo người dưới quá nhiều', 'rút lui vì tự ti'],
  },
  {
    slug: 'patient_deep',
    viLabel: 'Nhẫn nhịn, thâm trầm',
    viDescription: 'Chịu đựng lâu dài, lập kế hoạch từ xa; đến lúc mới ra tay.',
    voiceHints: 'Câu chậm rãi; nội tâm nhiều suy ngẫm; mô tả thời gian dài.',
    decisionStyle: 'Plan dài hạn; chờ đúng thời cơ; không bị khiêu khích.',
    dialogueStyle: 'Lịch sự với mọi đối tượng; ít lộ thái độ; nói nửa vời.',
    conflictResponse: 'Nuốt giận; ghi nhớ; chờ thời cơ phản công có chủ đích.',
    driftSignals: ['phản ứng bốc đồng', 'để lộ thái độ thật quá sớm', 'để cảm xúc lấn át kế hoạch'],
  },
  {
    slug: 'ruthless_antihero',
    viLabel: 'Tàn nhẫn, phản anh hùng',
    viDescription: 'Sẵn sàng dùng thủ đoạn tàn ác để đạt mục tiêu; không màng đạo đức xã hội.',
    voiceHints: 'Câu lạnh lùng có tính phán quyết; ít từ cảm xúc tích cực.',
    decisionStyle: 'Tính toán cost theo mục tiêu cá nhân; đạo đức công cộng không phải priority.',
    dialogueStyle: 'Trực tiếp, không che giấu mục đích; có thể đe doạ thẳng.',
    conflictResponse: 'Loại bỏ vĩnh viễn nếu cần; không nương tay; không thương lượng nếu bất lợi.',
    driftSignals: ['hối hận quá sớm', 'tha thứ vô lý', 'làm việc thiện không có mục đích chiến lược'],
  },
  {
    slug: 'kind_loyal',
    viLabel: 'Tốt bụng, trọng tình nghĩa',
    viDescription: 'Đặt người thân/bạn bè lên trên mình; trọng tình hơn lý.',
    voiceHints: 'Câu ấm áp; nội tâm nghĩ về người khác trước; cảm thán thiện chí.',
    decisionStyle: 'Ưu tiên người thân; sẵn sàng hi sinh lợi ích cá nhân.',
    dialogueStyle: 'Quan tâm; hời han; lắng nghe.',
    conflictResponse: 'Thiên về hoà giải; chỉ mạnh tay khi người thân bị tổn hại.',
    driftSignals: ['lạnh nhạt với bạn thân', 'tính toán tiền bạc với gia đình', 'phản bội bạn bè vì lợi'],
  },
  {
    slug: 'lonely_paranoid',
    viLabel: 'Cô độc, đa nghi',
    viDescription: 'Khó tin người; thích một mình; luôn cảnh giác.',
    voiceHints: 'Câu cẩn trọng; nội tâm hay đặt câu hỏi về động cơ người khác.',
    decisionStyle: 'Backup plan triple; không tin một nguồn thông tin duy nhất.',
    dialogueStyle: 'Ít chia sẻ thông tin; trả lời câu hỏi bằng câu hỏi; thử người đối thoại.',
    conflictResponse: 'Đề phòng từ trước; chuẩn bị exit; không trust ai dễ dàng.',
    driftSignals: ['tin người mới quá nhanh', 'chia sẻ thông tin nhạy cảm', 'kết bạn vô tư', 'giao tài sản cho người lạ'],
  },
  {
    slug: 'arrogant_confident',
    viLabel: 'Kiêu ngạo, tự tin',
    viDescription: 'Tin vào năng lực bản thân; coi người khác thấp hơn; không sợ ai.',
    voiceHints: 'Câu khẳng định cao; có chút khinh thường người khác; nội tâm tự tán dương.',
    decisionStyle: 'Tin gut feeling; ít tham khảo; coi rủi ro nhỏ.',
    dialogueStyle: 'Phán xét; thẳng thừng; gọi người khác bằng nickname xem thường.',
    conflictResponse: 'Đối đầu trực tiếp; không xuống nước; ăn miếng trả miếng.',
    driftSignals: ['xin lỗi vô cớ', 'nhường người yếu hơn', 'tự ti', 'do dự khi phải khoe tài'],
  },
  {
    slug: 'smart_strategist',
    viLabel: 'Thông minh, mưu lược',
    viDescription: 'Tính toán nhiều bước; thấy bức tranh lớn; ra quyết định dựa trên model.',
    voiceHints: 'Câu logic; nội tâm phân tích nhiều biến; hay so sánh tình huống với case study.',
    decisionStyle: 'Multi-step planning; weight rủi ro/lợi ích; tính toán phản ứng đối thủ.',
    dialogueStyle: 'Sử dụng câu hỏi dẫn dắt; ít lộ ý đồ; điều khiển dòng hội thoại.',
    conflictResponse: 'Thiết lập leverage trước khi va chạm; thắng từ outside; tránh trận đối đầu trực diện.',
    driftSignals: ['phản ứng bốc đồng', 'không có kế hoạch B', 'lộ ý đồ quá sớm', 'tin vào may mắn'],
  },
  {
    slug: 'naive_growing',
    viLabel: 'Ngây thơ nhưng trưởng thành dần',
    viDescription: 'Bắt đầu thuần khiết, dần học cách thực tế qua các va chạm.',
    voiceHints: 'Giai đoạn đầu: câu hỏi nhiều, ngạc nhiên; giai đoạn sau: chín chắn dần.',
    decisionStyle: 'Đầu: cảm tính, dễ tin. Sau: cẩn trọng hơn, học từ sai lầm.',
    dialogueStyle: 'Đầu: ngây thơ, hỏi nhiều. Sau: ít hỏi hơn, có chính kiến.',
    conflictResponse: 'Đầu: bị động, lúng túng. Sau: chủ động hơn.',
    driftSignals: ['stagnant không trưởng thành sau nhiều va chạm', 'quá chín chắn từ chương đầu', 'mất nét ngây thơ quá nhanh không có sự kiện'],
  },
  {
    slug: 'tram_on',
    viLabel: 'Trầm ổn, có trách nhiệm',
    viDescription: 'Bình tĩnh, đáng tin cậy, ra quyết định có suy xét.',
    voiceHints: 'Câu cân bằng, không cường điệu; nội tâm có cân nhắc.',
    decisionStyle: 'Trách nhiệm trước, lợi ích cá nhân sau.',
    dialogueStyle: 'Lịch sự, rõ ràng, không lươn lẹo.',
    conflictResponse: 'Đối mặt trực tiếp nhưng không liều lĩnh.',
    driftSignals: ['bốc đồng', 'tránh né trách nhiệm', 'cảm xúc cường điệu'],
  },
  {
    slug: 'mildly_unhinged',
    viLabel: 'Điên nhẹ, khó đoán',
    viDescription: 'Tâm lý không hoàn toàn ổn định; phản ứng bất thường; charm pha với nguy hiểm.',
    voiceHints: 'Câu xen kẽ logic và phi logic; cảm thán bất ngờ; nội tâm hỗn loạn nhẹ.',
    decisionStyle: 'Trực giác bốc đồng; không nhất quán giữa các lần tương tác.',
    dialogueStyle: 'Cười không đúng lúc; nói chủ đề lệch; có moment lạnh sống lưng.',
    conflictResponse: 'Bất ngờ; đối thủ không đoán được; có thể tự gây tổn thương.',
    driftSignals: ['quá ổn định cả nhiều chương', 'phản ứng predictable', 'mất chất "điên" trong action'],
  },
  {
    slug: 'lazy_talented',
    viLabel: 'Cá mặn, lười nhưng có tài',
    viDescription: 'Có năng lực thật nhưng lười biếng; chỉ nỗ lực khi bắt buộc.',
    voiceHints: 'Câu uể oải; cảm thán "phiền phức"; nội tâm muốn nằm ngủ.',
    decisionStyle: 'Chọn giải pháp ít tốn năng lượng nhất; trì hoãn đến phút cuối.',
    dialogueStyle: 'Lười biếng; nói cộc; than vãn; mỉa mai sự cần mẫn của người khác.',
    conflictResponse: 'Né tránh nếu được; nếu phải, dùng full skill và end nhanh để về nghỉ.',
    driftSignals: ['cần mẫn không lý do', 'tự nguyện làm việc tốn sức', 'mất thái độ "phiền phức"'],
  },
  {
    slug: 'cautious_survivalist',
    viLabel: 'Cẩn thận, sống sót là trên hết',
    viDescription: 'Ưu tiên sống sót; risk-averse; backup plan nhiều lớp.',
    voiceHints: 'Câu cẩn trọng; nội tâm hay đánh giá rủi ro; kế hoạch chi tiết.',
    decisionStyle: 'Chọn an toàn hơn glory; rút lui nếu rủi ro chết cao.',
    dialogueStyle: 'Cẩn thận về thông tin; ít hứa hẹn; hỏi câu hỏi an toàn.',
    conflictResponse: 'Tránh nếu có thể; nếu phải, đảm bảo có exit; không màng danh dự.',
    driftSignals: ['liều lĩnh vì danh dự', 'không có exit plan', 'chấp nhận rủi ro chết vì người lạ'],
  },
  {
    slug: 'vengeful_obsessed',
    viLabel: 'Báo thù, chấp niệm sâu',
    viDescription: 'Có một mối thù hoặc mục tiêu ám ảnh chi phối mọi quyết định.',
    voiceHints: 'Câu mang tone căm hận khi nhắc đối tượng; nội tâm hay quay về ký ức cũ.',
    decisionStyle: 'Mọi action đo bằng "có giúp gần báo thù không"; sacrifice khác miễn báo thù được.',
    dialogueStyle: 'Lạnh khi nói chuyện về thù; tránh chủ đề khi nguy cơ lộ; có moment bùng phát.',
    conflictResponse: 'Nếu liên quan thù: tất tay. Nếu không: né, dồn năng lượng cho mục tiêu chính.',
    driftSignals: ['quên báo thù vì romance dễ dãi', 'tha thứ kẻ thù không có lý do mạnh', 'mất focus vào mục tiêu'],
  },
  {
    slug: 'righteous_not_naive',
    viLabel: 'Chính đạo nhưng không ngu',
    viDescription: 'Trung thực và đứng về lẽ phải, nhưng đủ thông minh để không bị lợi dụng.',
    voiceHints: 'Câu chân thành nhưng có kiểm tra; cảm thán có ngữ cảnh.',
    decisionStyle: 'Đúng-sai làm trục, nhưng tính cả hậu quả; không hi sinh vô lý.',
    dialogueStyle: 'Thẳng thắn nhưng chọn timing; không phán xét vội.',
    conflictResponse: 'Đứng về lẽ phải nhưng có chuẩn bị; không lao vào bẫy.',
    driftSignals: ['hi sinh vô lý vì người lạ', 'bỏ qua bẫy hiển nhiên', 'tin vào lời hứa đối thủ'],
  },
  {
    slug: 'redeemed_villain',
    viLabel: 'Phản diện cải tà quy chính',
    viDescription: 'Từng làm điều ác, đang trên đường chuộc lỗi nhưng quá khứ vẫn ám ảnh.',
    voiceHints: 'Câu mang gánh nặng; nội tâm hay quay về ký ức tội lỗi; ít cảm thán tích cực.',
    decisionStyle: 'Cố gắng làm điều đúng, nhưng dùng kỹ năng cũ khi cần; không từ chối phương pháp tàn nhẫn.',
    dialogueStyle: 'Cẩn trọng khi đề cập quá khứ; có moment thật; không tự bào chữa.',
    conflictResponse: 'Cố giải quyết hoà bình trước; nếu cần, dùng kỹ năng phản diện cũ — và sau đó tự dằn vặt.',
    driftSignals: ['không bao giờ nhắc quá khứ', 'không có dằn vặt', 'rơi vào điều ác mà không có lý do mạnh'],
  },
];
