export const CONTEXT_CONFIG = {
  TOKEN_BUDGET_NORMAL: 6000,
  TOKEN_BUDGET_IMPORTANT: 10000,
  TOKEN_BUDGET_HOT_TARGET: 2500,
  TOKEN_BUDGET_WARM_TARGET: 2000,
  TOKEN_BUDGET_COLD_TARGET: 1500,

  RECENT_CHAPTER_SUMMARIES_COUNT: 5,
  RETRIEVED_CANON_FACTS_TOP_K: 8,
  RETRIEVED_PAST_CHAPTERS_TOP_K: 3,
  RETRIEVED_PAST_CHAPTERS_MIN_GAP: 5,
  RETRIEVAL_MIN_IMPORTANCE: ['high', 'locked'] as const,

  STYLE_FEWSHOT_COUNT: 3,
  STYLE_FEWSHOT_MAX_TOKENS_EACH: 250,

  ARC_ROLLING_SUMMARY_REFRESH_EVERY_N_CHAPTERS: 5,
  SAGA_ROLLING_SUMMARY_REFRESH_EVERY_N_CHAPTERS: 20,
  CHAPTER_SHORT_SUMMARY_TARGET_TOKENS: 200,
  CHAPTER_DETAILED_SUMMARY_TARGET_TOKENS: 500,

  PAST_REFERENCE_KEYWORDS: ['lần trước', 'trước đây', 'năm xưa', 'thuở nhỏ', 'kiếp trước', 'callback'],
  PAST_REFERENCE_USE_LLM_CLASSIFIER: false,

  SHRINK_ORDER: [
    'retrievedPastChapters',
    'retrievedFacts',
    'recentSummaries',
    'activeCharactersCompactMode',
  ] as const,
} as const;

export type ContextConfig = typeof CONTEXT_CONFIG;