export const GENERATION_CONFIG = {
  CHAPTER_TARGET_WORDS_MIN: 2000,
  CHAPTER_TARGET_WORDS_MAX: 3000,
  CHAPTER_HARD_FAIL_WORDS_MIN: 1500,
  CHAPTER_HARD_FAIL_WORDS_MAX: 4000,

  MAX_REALM_JUMP_PER_CHAPTER: 3,
  MAX_REALM_JUMP_PER_ARC: 5,
  MAX_NEW_BLOODLINES_PER_ARC: 2,

  PACKET_REGENERATE_MAX_ATTEMPTS: 1,
  WRITER_RETRY_ON_API_ERROR: 3,
  AUTO_FIX_MAX_ATTEMPTS: 1,
  AUTO_FIX_TRIGGER_SEVERITIES: ["low", "medium"] as const,
  STOP_SEVERITIES: ["high", "critical"] as const,

  DETERMINISTIC_VALIDATOR_BLOCKING_ON_FAIL: true,
  LLM_VALIDATOR_TEMPERATURE: 0.1,
  WRITER_TEMPERATURE: 0.85,
  WRITER_TOP_P: 0.95,

  SAFE_MODE_BATCH_SIZE: 1,
  SEMI_AUTO_BATCH_SIZE: 5,
  FULL_AUTO_BATCH_SIZE: 30,

  HIGH_STAKES_REVIEW_AT_ARC_END: true,
  HIGH_STAKES_REVIEW_ON_CRITICAL: true,

  AUTO_ESCALATE_TO_SAFE_MODE: {
    FIRST_CHAPTER_OF_STORY: true,
    FIRST_CHAPTER_OF_ARC: true,
    LAST_CHAPTER_OF_ARC: true,
    ON_VALIDATOR_HIGH: true,
    ON_VALIDATOR_CRITICAL: true,
    ON_BLOCKING_CONFLICT: true,
  },
} as const;

export type GenerationConfig = typeof GENERATION_CONFIG;
